### ISSUE TITLE
Consider handing errors to callbacks rather than throwing

### ISSUE THREAD

**Issue by jtrussell** [evsheffield/node-donedone-api#1]
Proposed:

``` javascript
donedone_api.getPerson(/* params */, function(err, stuff) {
  if(err) {
    // ... whoops!
  }
  // yay!
});
```

Would help with playing nice with things like [async](https://github.com/caolan/async).

**Comment by evsheffield** [comment]
Good call. I'll definitely need to have this in order to perform some actions like full release builds which would require multiple chained API calls.
